In [ ]:
import sqlite3

# conectando/criando bd local
conexao = sqlite3.connect("financeiro.db")
cursor = conexao.cursor()

# criando  tabelas(empresas, clientes, ..., trasnferÃªncias)
cursor.execute("""
CREATE TABLE IF NOT EXISTS empresas (
    id_empresa INTEGER PRIMARY KEY,
    nome_fantasia TEXT NOT NULL,
    cnpj TEXT UNIQUE,
    data_fundacao DATE
);
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT,
    cpf TEXT UNIQUE
);
""")


cursor.execute("""
CREATE TABLE IF NOT EXISTS receitas (
    id_receita INTEGER PRIMARY KEY,
    id_empresa INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    categoria TEXT,
    valor REAL NOT NULL,
    data DATE,
    descricao TEXT,
    FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);
""")


cursor.execute("""
CREATE TABLE IF NOT EXISTS despesas (
    id_despesa INTEGER PRIMARY KEY,
    id_empresa INTEGER NOT NULL,
    id_cliente INTEGER,
    categoria TEXT,
    valor REAL NOT NULL,
    data DATE,
    descricao TEXT,
    FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);
""")


cursor.execute("""
CREATE TABLE IF NOT EXISTS orcamentos (
    id_orcamento INTEGER PRIMARY KEY,
    id_empresa INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    valor_estimado REAL NOT NULL,
    FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa)
);
""")


cursor.execute("""
CREATE TABLE IF NOT EXISTS transferencias (
    id_transferencia INTEGER PRIMARY KEY,
    id_empresa_origem INTEGER NOT NULL,
    id_empresa_destino INTEGER NOT NULL,
    tipo TEXT,
    valor REAL NOT NULL,
    data DATE,
    descricao TEXT,
    FOREIGN KEY (id_empresa_origem) REFERENCES empresas(id_empresa),
    FOREIGN KEY (id_empresa_destino) REFERENCES empresas(id_empresa)
);
""")